// TOP CUSTOMERSLIST OPERATION(Read)
export const MOST_VIEWED_REQUEST = 'MOST_VIEWED_REQUEST';
export const MOST_VIEWED_SUCCESS = 'MOST_VIEWED_SUCCESS';
export const MOST_VIEWED_FAIL = 'MOST_VIEWED_FAIL';

export const MOST_VIEWED_DETAIL_REQUEST = 'MOST_VIEWED_DETAIL_REQUEST';
export const MOST_VIEWED_DETAIL_SUCCESS = 'MOST_VIEWED_DETAIL_SUCCESS';
export const MOST_VIEWED_DETAIL_FAIL = 'MOST_VIEWED_FAIL';
